---
version: '{branch}-{build}'
skip_tags: true
max_jobs: 1
image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
# Uncomment the following line to show RDP info at beginning of job
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
clone_folder: c:\projects\mixxx-buildserver
configuration:
  - Release
  - Debug
environment:
  matrix:
    - platform: x64
    - platform: x86
matrix:
  fast_finish: false     # set this flag to true to immediately finish build once one of the jobs fails.
install:
 - cd %TEMP%
 - echo *** Downloading and installing ASIOSDK
 - curl -fsS -L -o asiosdk2.3.zip http://www.steinberg.net/sdk_downloads/asiosdk2.3.zip
 - curl -fsS -L -o qt-everywhere-opensource-src-4.8.7.zip http://download.qt-project.org/official_releases/qt/4.8/4.8.7/qt-everywhere-opensource-src-4.8.7.zip
 - cd c:\projects\mixxx-buildserver\build\pa_stable_v19_20140130\src\hostapi\asio
 - 7z x %TEMP%\asiosdk2.3.zip
 - rename ASIOSDK2.3 ASIOSDK
 - cd c:\projects\mixxx-buildserver\build\
 - 7z x %TEMP%\qt-everywhere-opensource-src-4.8.7.zip
 - cd c:\projects\mixxx-buildserver
build_script:
  - build_environment.bat %platform% %configuration%
test: off
on_success:
  - echo "*** SUCCESS ***"
on_failure:
  - echo "*** FAILURE ***"
on_finish:
  # Uncomment the following line if you don't want the build VM to be destroyed
  # and be able to RDP on it until a special “lock” file on VM desktop is deleted
  # The RDP session is limited by overall build time (60 min).
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - echo "*** DONE ***"
